spring.application.name=Smart-ChatBot

openapi.api.url=https://api.openai.com/v1/chat/completions
openapi.api.model=gpt-4o-mini
openapi.api.key =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

